xychart-beta
    title "Ofertas publicadas en Colombia durante el último mes"
    x-axis ["Java + Spring Boot", "Angular", "PostgreSQL", "Kafka"]
    y-axis "Numero de ofertas" 0 --> 650
    bar [238, 260, 574, 192]
    line [316, 316, 316, 316]
